#!/usr/bin/env bash
# Delete the port [::]:8080 and leave only the 80
sudo sed -i "s/listen 8080 default_server/listen 80 default_server/i" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080 default_server/listen [::]:80 default_server/i" /etc/nginx/sites-enabled/default
sudo service nginx restart
