#!/usr/bin/env bash
# Delete the port [::]:80 and leave only the 80

sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/i' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on/i;' /etc/nginx/sites-available/default
sudo service nginx restart
