#!/usr/bin/env bash
# Short change of 8080 to 80
sudo sed -i "s/listen 8080 default_server/listen 80 default_server/i" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080 default_server/listen [::]:80 default_server/i" /etc/nginx/sites-enabled/default
sudo service nginx status
