#!/usr/bin/env bash
# Loop print 10 Holberton School but in the 9 iteration print Hi
i=0
while [ $i -lt 10 ]; do

    if [ $i -eq 9 ]; then
	echo "Hi"
    fi

    echo "Holberton School"
    i=$((i+1))
done
