#!/usr/bin/env bash
# Loop with while in bash script
i=1
while [ $i -lt 21 ]; do
    echo "$i"

    case $i in
	4)
            echo "bad luck from China"
	    ;;
	8)
	    echo "bad luck from Japan"
	    ;;
	17)
            echo "bad luck from Italy"
	    ;;
    esac

    i=$((i+1))
done
