#!/usr/bin/env bash
# Print a message about the number iteration
hour=0
min=1
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]; do
	echo "$min"
	min=$((min + 1))
    done
    hour=$((hour + 1))
done
