#!/usr/bin/env bash
# Change the user and group of /etc/nginx to execute how that user
sudo pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo chown nginx:nginx -R /etc/nginx
sudo -u nginx service nginx restart
