#!/usr/bin/env bash
# Run Nginx as Nginx
sudo pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
sudo sed -i '1a user nginx;' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
